### ISSUE TITLE
uncategorized - some should definitely be in explicit

### ISSUE THREAD

**Issue by chuckreynolds** [chucknorris-io/chuck-api#21]
Examples.. I just queried common words like `sex` etc.

ID: `YuW99QyQRFGEYbqQp_TynA`
ID: `WT46EO86SGSFZNCwYBTsUg` _(this is basically a dupe of this one which is already in explicit cat: ID: `1NG5TxB4RGWaahnzOErUiw`)_
ID: `7w-LfoTwQNiNjIncQUsNIQ`
ID: `-9D4NaUIQOO_8b1s7sJTKA`
ID: `nTefmxfYRYa7v7n_1936NA`
ID: `zSHg9mMSQnKpyzNodYA8rA`
ID: `MkS3XX7yQT6UpPAltnySlw`
ID: `3EOemsGMSEKttDnddHyi9A`
ID: `yYAmRPoeSYKP2xu8jfx_BQ`
ID: `UqZU5KPAQy6foJ4cTvAoJA`
ID: `3avTbFR4QJa1x959VJrqVA`
ID: `t-fGDoDxRx6Njpy88Mi8uA`
ID: `ov5fl59UT-SgbxuP8LAreA`
ID: `VEDOQuIsSI-2CAgq3-2DaQ`
....etc

**Comment by matchilling** [comment]
@chuckreynolds thanks helping in cleaning up the database! All jokes have been tagged accordingly and `WT46EO86SGSFZNCwYBTsUg` has been deleted due to duplication.

As the amount of possible offensive facts is limited, I think for the time being the most straightforward way to tag them correctly is to just submit a pull request via GitHub as you did before and I will update them accordingly in the database.

**Comment by chuckreynolds** [comment]
are they all in code? did a quick look and didn't find them but I would have changed them if I saw them... am I missing something?  I'm down to open PR's w/ the changes but I wasn't sure how to change those lines in the DB.

**Comment by matchilling** [comment]
The app is using a PostgreSQL database (see [chuck-db](https://github.com/chucknorris-io/chuck-db)). So you won't find any facts hard coded facts in the application code.

What I meant was, just open pull requests when you find issues like spelling/ wrong categorisation etc as you go and I will update them manually as there is no CRUD functionality available at the moment. It would be great if you could batch the changes though.
