### ISSUE TITLE
Telegram Bot 

### ISSUE THREAD

**Issue by UdoKifferbrehl** [chucknorris-io/chuck-api#5]
Hi, 
thank you so much for your awesome API. 
Do you know if there is already a Telegram bot which uses your API?

**Comment by matchilling** [comment]
Hey @UdoKifferbrehl, sorry for they delayed reply. Seems like that the notification hasn't made it through. 

I'm currently working with @message-io to bring the chuck bot to more platforms. But in order to answer your question, I'm not sure if there is currently an implementation available for telegram.
